baseURL = "https://www.morgankiger.com/"
title = "Morgan Kiger"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
disableKinds = ["RSS"]

[params]
  author = "Morgan Kiger"
  description = '<a href="mailto:kiger@unlv.nevada.edu">Email</a> &nbsp; • &nbsp;  <a href="/resume/morgan_kiger_resume.pdf">Resumè</a> &nbsp; • &nbsp; <a href="https://www.linkedin.com/in/morgan-kiger-84735573">LinkedIn</a> &nbsp; • &nbsp; <a href="https://github.com/mkiger95/portfolio">Portfolio</a>'
  logo = "fa-diamond"

[[params.social]]
	medium = "email"
	icon = "envelope-o"
	link = "mailto:kiger@unlv.nevada.edu"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/morgan-kiger-84735573"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/mkiger95"

[blackfriday]
  hrefTargetBlank = true

