baseURL = "https://www.morgankiger.com/"
title = "Morgan Kiger"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
disableKinds = ["RSS"]

[params]
  author = "Morgan Kiger"
  description = 'A website about me and links to work I have done in the past'
  logo = "fa-diamond"

[[params.social]]
	title = "email"
	icon = "envelope-o"
	url = "mailto:kiger@unlv.nevada.edu"

[[params.social]]
  title = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/morgan-kiger-84735573/"

[[params.social]]
  title = "github"
  icon = "github"
  link = "https://github.com/mkiger95/portfolio"
