baseURL = "https://www.morgankiger.com/"
title = "Morgan Kiger's Portfolio"
theme = "landing-page"
languageCode = "en-us"
defaultContentLanguage = "en"
disableKinds = ["RSS"]

[params]
  author = "Morgan Kiger"
  description = '<!--[-->A website about Morgan Kiger and work he has done<!--]-->'

[[params.social]]
	title = "email"
	icon = "envelope-o"
	url = "mailto:kiger@unlv.nevada.edu"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/morgan-kiger-84735573/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/mkiger95/portfolio"

